version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: workout_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: workout
      MYSQL_USER: workout_user
      MYSQL_PASSWORD: workout_pass
    ports:
      - "3306:3306"
    command: [
      "--default-authentication-plugin=caching_sha2_password",
      "--lower_case_table_names=1",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 30
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
