package com.jtucke3.workoutapi.domain.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.annotations.UuidGenerator;
import org.hibernate.type.SqlTypes;

import java.time.Instant;
import java.util.UUID;

import com.jtucke3.workoutapi.domain.enums.WeightUnit;

@Entity @Table(name = "users")
@Getter @Setter @NoArgsConstructor
public class UserEntity {

    @Id
    @UuidGenerator
    @JdbcTypeCode(SqlTypes.CHAR)              // <-- store UUID as 36-char string
    @Column(columnDefinition = "char(36)")
    private UUID id;

    @Column(nullable = false, unique = true)
    private String email;

    @Column(name = "password_hash", nullable = false)
    private String passwordHash;

    private String displayName;
    
    // username was referenced by service code but did not exist on the entity yet.
    // Add it now so setters/getters generated by Lombok are available.
    @Column(unique = true)
    private String username;

    @Column(nullable = false)
    private Instant createdAt = Instant.now();

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private WeightUnit preferredUnit = WeightUnit.POUNDS;
    
    @Column(name = "two_factor_enabled", nullable = false)
    private boolean twoFactorEnabled = false;

    @Column(name = "two_factor_secret")
    private String twoFactorSecret;
}
